name: Benchmark
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        timeout-minutes: 3
      - name: Clone test vectors
        timeout-minutes: 2
        uses: ./.github/actions/fetch-vectors

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.12"

      - name: Create virtualenv
        run: |
          python -m venv .venv
          .venv/bin/pip install -v -c ./ci-constraints-requirements.txt "./[test]" ./vectors/

      # - name: Run benchmarks staging
      #   uses: CodSpeedHQ/action@v2
      #   with:
      #     token: ${{ secrets.STAGING_CODSPEED_TOKEN }}
      #     upload-url: https://api.staging.preview.codspeed.io/upload
      #     run: .venv/bin/pytest --codspeed --benchmark-enable --benchmark-only ./tests/bench/ --benchmark-json=bench-pr.json --x509-limbo-root=x509-limbo/

      - name: Run benchmarks dev
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.DEV_GUILLAUME_CODSPEED_TOKEN }}
          upload-url: https://vpskktkxa2.execute-api.eu-west-1.amazonaws.com/upload

          run: .venv/bin/pytest --codspeed --benchmark-enable --benchmark-only ./tests/bench/ --benchmark-json=bench-pr.json --x509-limbo-root=x509-limbo/

      # - name: Run benchmarks prod
      #   uses: CodSpeedHQ/action@v2
      #   with:
      #     token: ${{ secrets.CODSPEED_TOKEN }}
      #     run: .venv/bin/pytest --codspeed --benchmark-enable --benchmark-only ./tests/bench/ --benchmark-json=bench-pr.json --x509-limbo-root=x509-limbo/

